### ISSUE TITLE
Referee Page DropDownLists are not filling out correctly.

### ISSUE THREAD

**Issue by tadams0** [tadams0/DebateSchedulerFinal#1]
The DropDownLists in the Referee page do not fill out sometimes, some of them are blank when loading the page. The scores are still saved correctly though.

**Comment by ProgenitorG** [comment]
Fixed. Changed the initial SelectedIndex of the Drop Down Lists to debate.Team1Score + 1 or debate.Team2Score + 1 (buffering for the unscored option).
