### ISSUE TITLE
News Pages in bad order

### ISSUE THREAD

**Issue by iAmGiG** [tadams0/DebateSchedulerFinal#6]
When news is placed on the news page, the order is not descending correctly. The order should be most recent at top, but is not. Should be fix on current build

**Comment by tadams0** [comment]
I fixed this issue by reversing the order of how news posts are displayed in [this commit.](https://github.com/tadams0/DebateSchedulerFinal/commit/d3d5cd6cca425ed2c7eab8be3293418e5bebc119)
